schema: remote-schema.graphql
extensions:
  endpoints:
    Parabolic Betting API:
      url: https://parabolic-snowy-cloud-5094.fly.dev/graphql
      headers:
        user-agent: JS GraphQL
      introspect: true
